basePath: /
definitions:
  models.Event:
    properties:
      agendaIds:
        items:
          type: string
        type: array
      description:
        type: string
      end:
        type: string
      id:
        type: string
      lastUpdate:
        type: string
      location:
        type: string
      name:
        type: string
      start:
        type: string
      uid:
        type: string
    type: object
info:
  contact:
    email: justine.bachelard@ext.uca.fr
    name: Justine Bachelard.
  description: API to manage users.
  title: middleware/example
  version: 1.0.0
paths:
  /events:
    get:
      description: Get all events.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "500":
          description: Something went wrong
      summary: Get all events.
      tags:
      - events
  /events/{id}:
    get:
      description: Get an event by its ID.
      parameters:
      - description: Event UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Get an event.
      tags:
      - events
schemes:
- http
swagger: "2.0"
